/*
 * This file was auto-generated by the sun-times-to-code.py script.
 * Generated on the 2022-01-15 21:37:10.377085.
 */

extern const int OC_TIME_JANUARY[31][4];
extern const int OC_TIME_FEBRUARY[31][4];
extern const int OC_TIME_MARCH[31][4];
extern const int OC_TIME_APRIL[31][4];
extern const int OC_TIME_MAY[31][4];
extern const int OC_TIME_JUNE[31][4];
extern const int OC_TIME_JULY[31][4];
extern const int OC_TIME_AUGUST[31][4];
extern const int OC_TIME_SEPTEMBER[31][4];
extern const int OC_TIME_OCTOBER[31][4];
extern const int OC_TIME_NOVEMBER[31][4];

