/*
 * This file was auto-generated by the sun-times-to-code.py script.
 * Generated on the 2022-01-16 14:20:07.966035.
 */

// Wrapper to allow clean typedef
typedef struct OcTableWrapper {
    int month[31][4];
};

// Structure to access months via array index 0 to 11
extern const OcTableWrapper* OPEN_CLOSE_MONTHS[12];

extern const OcTableWrapper OC_TIMES_JANUARY;
extern const OcTableWrapper OC_TIMES_FEBRUARY;
extern const OcTableWrapper OC_TIMES_MARCH;
extern const OcTableWrapper OC_TIMES_APRIL;
extern const OcTableWrapper OC_TIMES_MAY;
extern const OcTableWrapper OC_TIMES_JUNE;
extern const OcTableWrapper OC_TIMES_JULY;
extern const OcTableWrapper OC_TIMES_AUGUST;
extern const OcTableWrapper OC_TIMES_SEPTEMBER;
extern const OcTableWrapper OC_TIMES_OCTOBER;
extern const OcTableWrapper OC_TIMES_NOVEMBER;
extern const OcTableWrapper OC_TIMES_DECEMBER;